name: transfer_env
channels:
  - defaults
  - conda-forge
dependencies:
  - boto3
  - botocore
  - brotli-python
  - bzip2
  - ca-certificates
  - jmespath
  - libcxx
  - libffi
  - ncurses
  - openssl
  - pip
  - psycopg
  - pysocks
  - python
  - python-dateutil
  - python-dotenv
  - readline
  - s3transfer
  - setuptools
  - six
  - sqlite
  - tk
  - tzdata
  - urllib3
  - wheel
  - xz
  - zlib

